# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        UM2\UserBundle\Entity\User: 
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        our_db_provider:
            entity:
                class: UM2\UserBundle\Entity\User
                property: email
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            user_checker: UM2\UserBundle\Security\UserChecker
            http_basic: ~
            anonymous:    true
            provider: our_db_provider
            form_login:
                login_path: um2_user_login
                check_path: um2_user_login
                default_target_path: /
            logout:
                path: um2_user_logout
                target: /login

        secured_area:
            # ...
            form_login:
                # ...
                csrf_token_generator: security.csrf.token_manager
                csrf_parameter: _csrf_security_token
                csrf_token_id: a_private_string

    access_control:
        - {path: ^/admin, roles: ROLE_SUPER_ADMIN}
        - {path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    always_authenticate_before_granting: true